config/routes.rb
Rails.application.routes.draw do
  root to: 'translation#index'
  resources :translation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/translation_controller.rb
class TranslationController < ApplicationController

  def index
    @traducao = Translation.all
  end

  def show
    id = params[:id]
    @traducao = Translation.find(id)
  end

  def new
    @traducao = Translation.new
  end

  def create
    @traducao = Translation.new
    @traducao.texto_portugues = params[:translation][:texto_portugues]
    @traducao.texto_ingles = params[:translation][:texto_ingles]
    @traducao.save
    redirect_to root_path
  end

  def edit
    id = params[:id]
    @traducao = Translation.find(id)
  end

  def update
    id = params[:translation][:id]
    @traducao = Translation.find(id)
    @traducao.update_attributes(:texto_portugues => params[:translation][:texto_portugues], :texto_ingles => params[:translation][:texto_ingles])
    redirect_to root_path
  end

  def destroy
    id = params[:id]
    @traducao = Translation.find(id)
    @traducao.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translation_helper.rb
module TranslationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tradutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/translation/edit.html.erb
<h2 class="text-center">Tradutor de palavras Campus Code</h2>
<div class="panel panel-primary">
  <div class="panel-heading" style="padding-bottom:20px;">
    Alterar tradução
    <%= link_to ('Voltar').html_safe, root_path,:class=>"btn btn-default pull-right"  %>
  </div>
  <%= form_for(@traducao, url: '/translation/:id') do |f| %>
    <%= f.hidden_field :id %>
    <div class="form-group">
      <%= f.label :texto_portugues %>
      <%= f.text_field :texto_portugues, :class=>"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :texto_ingles %>
      <%= f.text_field :texto_ingles, :class=>"form-control" %>
    </div>
    <%= f.submit "Alterar",:class=>"btn btn-success" %>
  <% end %>

</div>

app/views/translation/index.html.erb
<h2 class="text-center">Tradutor de palavras Campus Code</h2>
<div class="panel panel-primary">
  <div class="panel-heading"  style="padding-bottom:20px;">
    Lista de Traduções
    <%= link_to ('Novo').html_safe, new_translation_path, :class=>"btn btn-default pull-right" %>
  </div>
    <table class="table">
      <thead>
          <tr>
          <th>#</th>
          <th>Palavras</th>
          <th>Vizualizar Traducao</th>
          <th>Editar</th>
          <th>Deletar</th>
        </tr>
      </thead>
      <tbody>
    <% @traducao.each do |traducao| %>
        <tr>
          <td>
            <%= traducao.id %>
          </td>
          <td>
            <%= traducao.texto_ingles %>
          </td>
          <td>
            <%= link_to ('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>').html_safe, translation_path(traducao.id) %>
          </td>
          <td>
            <%= link_to ('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>').html_safe, edit_translation_path(traducao.id) %>
          </td>
          <td>
            <%= link_to ('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>').html_safe, { action: :destroy, id: traducao.id }, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir?' }  %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>
</div>

app/views/translation/new.html.erb
<h2 class="text-center">Tradutor de palavras Campus Code</h2>
<div class="panel panel-primary">
  <div class="panel-heading" style="padding-bottom:20px;">
    Inserir tradução
    <%= link_to ('Voltar').html_safe, root_path,:class=>"btn btn-default pull-right"  %>
  </div>
  <%= form_for(@traducao, url: '/translation') do |f| %>
    <div class="form-group">
      <%= f.label :texto_portugues %>
      <%= f.text_field :texto_portugues, :class=>"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :texto_ingles %>
      <%= f.text_field :texto_ingles, :class=>"form-control" %>
    </div>
    <%= f.submit "Inserir",:class=>"btn btn-success" %>
  <% end %>

</div>

app/views/translation/show.html.erb
<h2 class="text-center">Tradutor de palavras Campus Code</h2>
<div class="panel panel-primary">
  <div class="panel-heading" style="padding-bottom:20px;">
    Vizualiar Tradução
    <%= link_to ('Voltar').html_safe, root_path,:class=>"btn btn-default pull-right"  %>
  </div>
    <p class="text-center">
      A tradução de <b><%=@traducao.texto_ingles%></b> é <b><%=@traducao.texto_portugues%></b>
    </p>
</div>